name: DotNet App CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
#   build:
#     runs-on: windows-latest
#     steps:
#       - uses: actions/checkout@v2
      
#       - name: Setup MS Build
#         uses: microsoft/setup-msbuild@v1.1
        
#       - name: Setup NuGet
#         uses: NuGet/setup-nuget@v1.0.5
        
#       - name: Restore NuGet Packages
#         run: nuget restore DotNetApp.sln
        
#       - name: Build the solution
#         run: msbuild DotNetApp.sln /p:Configuration=Release

  
  Version: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2  
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
      
       # Manually set the version number you want to use
     - name: Set Version Number
       run: |
          # Replace <your_version> with the desired version number
          echo "export APP_VERSION=<your_version>" >> $GITHUB_ENV

     - name: Check for Dockerfile changes
       run: |
          # Check if the Dockerfile contains the placeholder for version number
          if grep -q '{{VERSION}}' Dockerfile; then
            # Replace the placeholder in the Dockerfile with the specified version number
            sed -i "s/{{VERSION}}/$APP_VERSION/g" Dockerfile
          else
            echo "Dockerfile does not contain the version placeholder '{{VERSION}}'. Skipping update."
          fi

     - name: Commit and Push Changes
       run: |
          git config --local user.email "hariskhattak584@gmail.com"
          git config --local user.name "Haris-584"
          git add Dockerfile

          # Check if there are any changes to commit
          if git diff --staged --quiet; then
            echo "No changes in the Dockerfile. Skipping commit."
          else
            git commit -m "Update Dockerfile version number" Dockerfile
            git push
          fi
          
          
          
          
          
#   Docker: 
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v2  
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
      
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#            username: ${{ secrets.DOCKER_USERNAME }}
#            password: ${{ secrets.DOCKER_PASSWORD }}   
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#             push: true
#             tags: 899889988998/demo-app:latest
