name: DotNet App CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup MS Build
        uses: microsoft/setup-msbuild@v1.1
        
      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5
        
      - name: Restore NuGet Packages
        run: nuget restore DotNetApp.sln
        
      - name: Build the solution
        run: msbuild DotNetApp.sln /p:Configuration=Release

  
  Version: 
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v2  
     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2
      
     - name: Update Dockerfile Version
       run: |
          # Fetch the latest tag from the repository (assuming you use tags for versioning)
          latest_version=$(git describe --tags $(git rev-list --tags --max-count=1))

          # Replace the placeholder in the Dockerfile with the latest version number
          sed -i "s/{{VERSION}}/${latest_version}/g" Dockerfile
          
       # Add more steps here for building and pushing Docker images if desired

     - name: Commit and Push Changes
       run: |
          git config --local user.email "hariskhattak584@github.com"
          git config --local user.name "Haris-584"
          git commit -m "Update Dockerfile version number" Dockerfile
          git push
          
          
          
          
          
          
#   Docker: 
#     runs-on: ubuntu-latest
#     steps:
#      - uses: actions/checkout@v2  
#      - name: Set up Docker Buildx
#        uses: docker/setup-buildx-action@v2
      
#      - name: Login to Docker Hub
#        uses: docker/login-action@v2
#        with:
#            username: ${{ secrets.DOCKER_USERNAME }}
#            password: ${{ secrets.DOCKER_PASSWORD }}   
#      - name: Build and push
#        uses: docker/build-push-action@v4
#        with:
#             push: true
#             tags: 899889988998/demo-app:latest
